repos:

  - repo: local
    hooks:
      - id: pytest
        name: run pytest
        entry: pytest -vv ./tests
        language: system
        types: [python]
        env:
          DATABASE_URL: "sqlite:///./test.db"
          CREATE_TABLES: true

      - id: pylint
        name: run pylint
        entry: pylint
        language: system
        types: [python]